### ISSUE TITLE
Image digest(s) as action output

### ISSUE THREAD

**Issue by mowies** [akhilerm/tag-push-action#169]
It would be amazing to have this action output the docker image digests for the destination images.

**Comment by akhilerm** [comment]
@mowies Since we are not building the image or changing the digest while copying the image, the digest can be already known from the registry itself.

Also, the digest will be different for different platform (amd64, arm64 etc). How should that be shown?

It will be better if you can describe your use case, so that I can find a solution.

**Comment by mowies** [comment]
I had a misunderstanding regarding the image digests. They don't change when you move them to a different registry right?
If that's the case, I think this issue can be closed.

**Comment by akhilerm** [comment]
> I had a misunderstanding regarding the image digests. They don't change when you move them to a different registry right? If that's the case, I think this issue can be closed.

Nope. The image digest does not change. That is the main aim of this project , to copy images to different registries without change in digest.
